### ISSUE TITLE
mcd removed from dapptools

### ISSUE THREAD

**Issue by TomWang10** [makerdao/mcd-cli#22]
Hi,
I want to install mcd-cli for testing MakerDao and I found mcd removed from dapptools

**Comment by brianmcmichael** [comment]
Hello, `mcd-cli` was removed from dapptools because some of the underlying dependencies had updated and `mcd-cli` required a substantial update.

It now includes an installer script, check the [README](https://github.com/makerdao/mcd-cli#installation) for details.
