### ISSUE TITLE
mawk fails to parse the ilk conf (and presumably others)

### ISSUE THREAD

**Issue by 00jw** [makerdao/mcd-cli#8]
`mawk` is the implementation of awk used in Debian and Ubuntu by default. Here's the error:

```$ mcd ilks
awk: run time error: improper conversion(number 3) in printf("%-5s %-5s %12-s")
FILENAME="/nix/store/kqspqplgq7gyy8qcaqgjm11ln0y7z7z5-mcd-0.2.2-rc.1/libexec/mcd/conf/ilks" FNR=1 NR=1
ILK      GEM
```

This can be worked around by installing gawk and ensuring it's set as the default awk instead of mawk. Due to the prevalence of Debian & Ubuntu, the lack of support seems like a bug.

**Comment by EdNoepel** [comment]
@desaperados fixed this: https://github.com/makerdao/mcd-cli/commit/d20a4f59b5402e8f01bcbbd58c10905096aefb13
